export const SET_USER_PREFS = 'SET_USER_PREFS';
export const UNSET_USER_PREFS = 'UNSET_USER_PREFS';
export const SET_TOKEN_INTERVAL_ID = 'SET_TOKEN_INTERVAL_ID';
export const SET_USER_AUTH = 'SET_USER_AUTH';
export const UNSET_USER_AUTH = 'UNSET_USER_AUTH';
export const SET_SELECTED_DATE = 'SET_SELECTED_DATE';
export const SET_FIREBASE_TOKEN = 'SET_FIREBASE_TOKEN';

export const SET_TOKEN_BOT_GO = 'SET_TOKEN_BOT_GO';
export const SET_AUTO_BOT_GO = 'SET_AUTO_BOT_GO';
export const SET_BENEFICIARIES = 'SET_BENEFICIARIES';
export const SET_BOOKING_PARAMS = 'SET_BOOKING_PARAMS';
export const SET_SLOT_INTERVAL_ID = 'SET_SLOT_INTERVAL_ID';
export const SET_SLOT_DETAILS = 'SET_SLOT_DETAILS';
export const SET_BOOKING = 'SET_BOOKING';
export const SET_STATUS = 'SET_STATUS';

export const ERROR = 'ERROR';
export const RESET_ERROR = 'RESET_ERROR';